name: 'Github Action Step Log Scanner'
description: 'Scan the logs of previous steps and fail on matched strings'
author: 'Jason Naylor'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'check'
  color: 'red'

# Define your inputs here.
inputs:
  error-regex:
    required: true
    description: 'Regex to identify errors'
  gh-token:
    required: false
    description: 'Github repo token'
    default: ${{ secrets.GITHUB_TOKEN }}
  run-id:
    required: false
    description: 'Github run ID'
    default: ${{ github.run_id }}
  repo-owner:
    required: false
    description: 'Repo owner for GitHub api calls'
    default: ${{ github.repository_owner }}
  repo-name:
    required: false
    description: 'Repo name for GitHub api calls'
    default: ${{ github.repository }}

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
