name: 'Github Action Step Log Scanner'
description: 'Scan the logs of previous steps and fail on matched strings'
author: 'Jason Naylor'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'check'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
